name: SpeedMC
version: 1.0
author: ThauanDeveloper
description: Plugin for SpeedMC
main: com.github.caaarlowsz.speedmc.kitpvp.Main
commands:
  kills:
  register:
  login:
  setarena:
  mudarsenha:
  build:
  dica:
  regras:
  perfil:
  money:
  setgroup:
  aviso:
  status:
  stats:
  builder:
  admin:
  aplicar:
  hg:
  loja:
  store:
  kit:
  giveall:
  ip:
  changeskin:
  removeall:
  score:
  fly:
  helpop:
  tag:
  tags:
  tp:
  gamemode:
  gm:
  youtuber:
  chat:
  setholograma:
  sc:
  ban:
  tempban:
  kick:
  pardon:
  mute:
  ipban:
  tempmute:
  dica:
  report:
  set:
  spawn:
  warp:
  speed1v1:
  tell:
   aliases: [msg]
  join:
  entrar:
  sair:
  leave:
  specs:
  ban:
  tempban:
  kick:
  pardon:
  mute:
  ipban:
  tempmute:
  bancheck:
  mutecheck:
  bc:
  account:
  inv:
  invsee:
  getip:
  horas:
  rank:
  liga:
  ranks:
  clarinha:
  fake:
  ping:
  acc:
  tpall:
  vis:
  invis:
  removerhead:
  removerhat:
  removehead:
  removehat:
  manutencao:
  cage:
  autosoup:
  tphere:
  s:
  stopserver:
  kickall:
  login:
  register:
  monitorar:
  skit:
  dano:
  pvp:
  clearall:
  head:
  addpermission:
  removepermission:
  givekills:
  givevip:
  giveyoutuber:
  givebuilder:
  givekit: